-- Demo catalogue (delete from Admin → Products when you add your real abayas)
insert into public.products (slug,name,tagline,description,price,compare_at_price,category_id,images,sizes,colors,material,care,stock,is_active,is_featured,created_at)
select 'noor-classic-black','Noor Classic Black','The everyday essential','A timeless flowing abaya cut from featherlight crepe with a relaxed drape, sheer-sleeve detail and a hem that moves beautifully. Designed to be worn on repeat.',8700,10500,(select id from public.categories where slug='everyday'),array['/demo/noor-classic-black.jpg','/demo/noor-classic-black-detail.jpg'],array['52','54','56','58','60'],'[{"name": "Jet Black", "hex": "#141414"}, {"name": "Charcoal", "hex": "#3d3d42"}]'::jsonb,'Premium crepe · 100% polyester','Gentle machine wash cold or dry clean. Steam to refresh. Do not bleach.',24,true,true,'2026-09-28T00:00:00Z'
where not exists (select 1 from public.products where slug='noor-classic-black');
insert into public.products (slug,name,tagline,description,price,compare_at_price,category_id,images,sizes,colors,material,care,stock,is_active,is_featured,created_at)
select 'layla-gold-cuff-open-front','Layla Gold-Cuff Open Front','Gold trim, quiet luxury','A satin-finish open-front abaya with gold-embroidered cuffs and a luminous drape. Layer it over anything for an instant statement.',13800,null,(select id from public.categories where slug='open-front'),array['/demo/layla-gold-cuff-open-front.jpg','/demo/layla-gold-cuff-open-front-detail.jpg'],array['52','54','56','58','60'],'[{"name": "Espresso", "hex": "#3b2a26"}, {"name": "Midnight", "hex": "#1b2340"}]'::jsonb,'Satin crepe · gold embroidered cuffs','Gentle machine wash cold or dry clean. Steam to refresh. Do not bleach.',12,true,true,'2026-09-27T00:00:00Z'
where not exists (select 1 from public.products where slug='layla-gold-cuff-open-front');
insert into public.products (slug,name,tagline,description,price,compare_at_price,category_id,images,sizes,colors,material,care,stock,is_active,is_featured,created_at)
select 'zahra-rose-open-front','Zahra Rose Open Front','Flow in every step','A soft rose open-front abaya with ruffled bell sleeves and a matching inner dress. Light, romantic and effortless to style.',11400,12900,(select id from public.categories where slug='open-front'),array['/demo/zahra-rose-open-front.jpg','/demo/zahra-rose-open-front-detail.jpg'],array['52','54','56','58','60'],'[{"name": "Rose", "hex": "#d9808f"}, {"name": "Ivory", "hex": "#ece4d6"}]'::jsonb,'Chiffon crepe','Gentle machine wash cold or dry clean. Steam to refresh. Do not bleach.',9,true,true,'2026-09-26T00:00:00Z'
where not exists (select 1 from public.products where slug='zahra-rose-open-front');
insert into public.products (slug,name,tagline,description,price,compare_at_price,category_id,images,sizes,colors,material,care,stock,is_active,is_featured,created_at)
select 'salma-mauve-butterfly','Salma Mauve Butterfly','Light as air','A generous butterfly cut in rich mauve with wide, airy sleeves and tonal beaded trim. The perfect Eid companion.',9900,null,(select id from public.categories where slug='occasion'),array['/demo/salma-mauve-butterfly.jpg','/demo/salma-mauve-butterfly-detail.jpg'],array['52','54','56','58','60'],'[{"name": "Mauve", "hex": "#8a5a7a"}, {"name": "Plum", "hex": "#4a2640"}]'::jsonb,'Soft crepe · beaded trim','Gentle machine wash cold or dry clean. Steam to refresh. Do not bleach.',15,true,true,'2026-09-25T00:00:00Z'
where not exists (select 1 from public.products where slug='salma-mauve-butterfly');
insert into public.products (slug,name,tagline,description,price,compare_at_price,category_id,images,sizes,colors,material,care,stock,is_active,is_featured,created_at)
select 'amira-navy-stripe-kimono','Amira Navy Stripe Kimono','Graphic, graceful, modern','A navy kimono-style abaya with sculpted blush stripes. Structured yet fluid — made for work and gatherings alike.',9600,null,(select id from public.categories where slug='everyday'),array['/demo/amira-navy-stripe-kimono.jpg','/demo/amira-navy-stripe-kimono-detail.jpg'],array['52','54','56','58','60'],'[{"name": "Navy", "hex": "#1a2447"}]'::jsonb,'Crepe with woven stripes','Gentle machine wash cold or dry clean. Steam to refresh. Do not bleach.',18,true,false,'2026-09-24T00:00:00Z'
where not exists (select 1 from public.products where slug='amira-navy-stripe-kimono');
insert into public.products (slug,name,tagline,description,price,compare_at_price,category_id,images,sizes,colors,material,care,stock,is_active,is_featured,created_at)
select 'mariam-ivory-lace-cuff','Mariam Ivory Lace Cuff','For the moments that matter','A pure ivory abaya with delicate lace-trimmed cuffs, floor length with a graceful sweep. Elegant for Eid, nikah and special evenings.',17700,20700,(select id from public.categories where slug='occasion'),array['/demo/mariam-ivory-lace-cuff.jpg','/demo/mariam-ivory-lace-cuff-detail.jpg'],array['52','54','56','58','60'],'[{"name": "Ivory", "hex": "#ece4d6"}]'::jsonb,'Silk-blend crepe · lace detail','Gentle machine wash cold or dry clean. Steam to refresh. Do not bleach.',6,true,true,'2026-09-23T00:00:00Z'
where not exists (select 1 from public.products where slug='mariam-ivory-lace-cuff');
insert into public.products (slug,name,tagline,description,price,compare_at_price,category_id,images,sizes,colors,material,care,stock,is_active,is_featured,created_at)
select 'dana-dusty-mauve','Dana Dusty Mauve','Made for warm days','A breathable dusty-mauve abaya with a relaxed shape and easy button front. Gets softer with every wear.',8100,null,(select id from public.categories where slug='everyday'),array['/demo/dana-dusty-mauve.jpg','/demo/dana-dusty-mauve-detail.jpg'],array['52','54','56','58','60'],'[{"name": "Dusty Mauve", "hex": "#a98390"}, {"name": "Stone", "hex": "#b9b3a4"}]'::jsonb,'Linen-viscose blend','Gentle machine wash cold or dry clean. Steam to refresh. Do not bleach.',20,true,false,'2026-09-22T00:00:00Z'
where not exists (select 1 from public.products where slug='dana-dusty-mauve');
insert into public.products (slug,name,tagline,description,price,compare_at_price,category_id,images,sizes,colors,material,care,stock,is_active,is_featured,created_at)
select 'hana-embroidered-black','Hana Embroidered Black','Detail you''ll want to touch','Classic black with tonal embroidery across the chest and cuffs. A statement that still feels modest and refined.',14900,null,(select id from public.categories where slug='embroidered'),array['/demo/hana-embroidered-black.jpg','/demo/hana-embroidered-black-detail.jpg'],array['52','54','56','58','60'],'[{"name": "Black", "hex": "#141414"}]'::jsonb,'Nida · machine embroidery','Gentle machine wash cold or dry clean. Steam to refresh. Do not bleach.',10,true,true,'2026-09-21T00:00:00Z'
where not exists (select 1 from public.products where slug='hana-embroidered-black');
insert into public.products (slug,name,tagline,description,price,compare_at_price,category_id,images,sizes,colors,material,care,stock,is_active,is_featured,created_at)
select 'noor-ornate-sleeve','Noor Ornate Sleeve','Heritage pattern, modern cut','Midnight black with richly patterned gold-and-black sleeve panels and matching edge trim. Worth every compliment.',15900,null,(select id from public.categories where slug='embroidered'),array['/demo/noor-ornate-sleeve.jpg','/demo/noor-ornate-sleeve-detail.jpg'],array['52','54','56','58','60'],'[{"name": "Black Gold", "hex": "#1b1511"}]'::jsonb,'Nida silk blend · jacquard trim','Gentle machine wash cold or dry clean. Steam to refresh. Do not bleach.',7,true,false,'2026-09-20T00:00:00Z'
where not exists (select 1 from public.products where slug='noor-ornate-sleeve');
insert into public.products (slug,name,tagline,description,price,compare_at_price,category_id,images,sizes,colors,material,care,stock,is_active,is_featured,created_at)
select 'inaya-rosewood-embroidered','Inaya Rosewood Embroidered','Warm, soft, unforgettable','A rosewood abaya with floral appliqué on the bell sleeves. Wide, graceful and full of movement.',13200,15000,(select id from public.categories where slug='embroidered'),array['/demo/inaya-rosewood-embroidered.jpg','/demo/inaya-rosewood-embroidered-detail.jpg'],array['52','54','56','58','60'],'[{"name": "Rosewood", "hex": "#8a5a4e"}]'::jsonb,'Crepe · appliqué embroidery','Gentle machine wash cold or dry clean. Steam to refresh. Do not bleach.',8,true,false,'2026-09-19T00:00:00Z'
where not exists (select 1 from public.products where slug='inaya-rosewood-embroidered');
insert into public.products (slug,name,tagline,description,price,compare_at_price,category_id,images,sizes,colors,material,care,stock,is_active,is_featured,created_at)
select 'sara-slate-swirl','Sara Slate Swirl','Soft grey, sculpted detail','A slate-grey abaya with swirling black embroidery on the shoulders and layered chiffon sleeves.',12300,null,(select id from public.categories where slug='embroidered'),array['/demo/sara-slate-swirl.jpg','/demo/sara-slate-swirl-detail.jpg'],array['52','54','56','58','60'],'[{"name": "Slate", "hex": "#4a4e55"}]'::jsonb,'Crepe with chiffon sleeves','Gentle machine wash cold or dry clean. Steam to refresh. Do not bleach.',0,true,false,'2026-09-18T00:00:00Z'
where not exists (select 1 from public.products where slug='sara-slate-swirl');
